[mypy]
namespace_packages = True
python_version = 3.11
mypy_path = src/python
explicit_package_bases = True

[mypy-linux_rag.contracts.*]
ignore_missing_imports = True

[mypy-linux_rag.llm.*]
ignore_missing_imports = True

[mypy-linux_rag.retrieval.*]
ignore_missing_imports = True
