// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: rag_service.proto

package contractspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueryText      string                 `protobuf:"bytes,1,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	ContextHints   []string               `protobuf:"bytes,2,rep,name=context_hints,json=contextHints,proto3" json:"context_hints,omitempty"`       // Optional keywords to bias retrieval
	PreferredModel string                 `protobuf:"bytes,3,opt,name=preferred_model,json=preferredModel,proto3" json:"preferred_model,omitempty"` // "gemma3:1b" or "codegemma:2b"
	AllowCache     bool                   `protobuf:"varint,4,opt,name=allow_cache,json=allowCache,proto3" json:"allow_cache,omitempty"`            // When false, force fresh generation
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AskRequest) Reset() {
	*x = AskRequest{}
	mi := &file_rag_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRequest) ProtoMessage() {}

func (x *AskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRequest.ProtoReflect.Descriptor instead.
func (*AskRequest) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{0}
}

func (x *AskRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *AskRequest) GetContextHints() []string {
	if x != nil {
		return x.ContextHints
	}
	return nil
}

func (x *AskRequest) GetPreferredModel() string {
	if x != nil {
		return x.PreferredModel
	}
	return ""
}

func (x *AskRequest) GetAllowCache() bool {
	if x != nil {
		return x.AllowCache
	}
	return false
}

type AskResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AnswerText     string                 `protobuf:"bytes,2,opt,name=answer_text,json=answerText,proto3" json:"answer_text,omitempty"`
	Citations      []*Citation            `protobuf:"bytes,3,rep,name=citations,proto3" json:"citations,omitempty"`
	CacheHit       bool                   `protobuf:"varint,4,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	ResponseTimeMs int64                  `protobuf:"varint,5,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AskResponse) Reset() {
	*x = AskResponse{}
	mi := &file_rag_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskResponse) ProtoMessage() {}

func (x *AskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskResponse.ProtoReflect.Descriptor instead.
func (*AskResponse) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{1}
}

func (x *AskResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AskResponse) GetAnswerText() string {
	if x != nil {
		return x.AnswerText
	}
	return ""
}

func (x *AskResponse) GetCitations() []*Citation {
	if x != nil {
		return x.Citations
	}
	return nil
}

func (x *AskResponse) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *AskResponse) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

type Citation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippet       string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	SourcePath    string                 `protobuf:"bytes,4,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Citation) Reset() {
	*x = Citation{}
	mi := &file_rag_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Citation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Citation) ProtoMessage() {}

func (x *Citation) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Citation.ProtoReflect.Descriptor instead.
func (*Citation) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{2}
}

func (x *Citation) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Citation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Citation) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *Citation) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

type RunIngestionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WikiArchiveIds  []string               `protobuf:"bytes,1,rep,name=wiki_archive_ids,json=wikiArchiveIds,proto3" json:"wiki_archive_ids,omitempty"` // Selected Kiwix archive identifiers
	RefreshManPages bool                   `protobuf:"varint,2,opt,name=refresh_man_pages,json=refreshManPages,proto3" json:"refresh_man_pages,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunIngestionRequest) Reset() {
	*x = RunIngestionRequest{}
	mi := &file_rag_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunIngestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunIngestionRequest) ProtoMessage() {}

func (x *RunIngestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunIngestionRequest.ProtoReflect.Descriptor instead.
func (*RunIngestionRequest) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{3}
}

func (x *RunIngestionRequest) GetWikiArchiveIds() []string {
	if x != nil {
		return x.WikiArchiveIds
	}
	return nil
}

func (x *RunIngestionRequest) GetRefreshManPages() bool {
	if x != nil {
		return x.RefreshManPages
	}
	return false
}

type RunIngestionResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	JobId                 string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ManPagesProcessed     int64                  `protobuf:"varint,2,opt,name=man_pages_processed,json=manPagesProcessed,proto3" json:"man_pages_processed,omitempty"`
	WikiArticlesProcessed int64                  `protobuf:"varint,3,opt,name=wiki_articles_processed,json=wikiArticlesProcessed,proto3" json:"wiki_articles_processed,omitempty"`
	Errors                []*IngestionError      `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RunIngestionResponse) Reset() {
	*x = RunIngestionResponse{}
	mi := &file_rag_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunIngestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunIngestionResponse) ProtoMessage() {}

func (x *RunIngestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunIngestionResponse.ProtoReflect.Descriptor instead.
func (*RunIngestionResponse) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{4}
}

func (x *RunIngestionResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunIngestionResponse) GetManPagesProcessed() int64 {
	if x != nil {
		return x.ManPagesProcessed
	}
	return 0
}

func (x *RunIngestionResponse) GetWikiArticlesProcessed() int64 {
	if x != nil {
		return x.WikiArticlesProcessed
	}
	return 0
}

func (x *RunIngestionResponse) GetErrors() []*IngestionError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type IngestionError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestionError) Reset() {
	*x = IngestionError{}
	mi := &file_rag_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionError) ProtoMessage() {}

func (x *IngestionError) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionError.ProtoReflect.Descriptor instead.
func (*IngestionError) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{5}
}

func (x *IngestionError) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IngestionError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_rag_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{6}
}

type IngestionProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Stage           string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`                                              // running, completed, failed, idle
	PercentComplete float64                `protobuf:"fixed64,2,opt,name=percent_complete,json=percentComplete,proto3" json:"percent_complete,omitempty"` // 0-100
	RetryCount      int64                  `protobuf:"varint,3,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`                 // number of retries attempted during the latest job
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IngestionProgress) Reset() {
	*x = IngestionProgress{}
	mi := &file_rag_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionProgress) ProtoMessage() {}

func (x *IngestionProgress) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionProgress.ProtoReflect.Descriptor instead.
func (*IngestionProgress) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{7}
}

func (x *IngestionProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *IngestionProgress) GetPercentComplete() float64 {
	if x != nil {
		return x.PercentComplete
	}
	return 0
}

func (x *IngestionProgress) GetRetryCount() int64 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type ScheduleSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cadence       string                 `protobuf:"bytes,1,opt,name=cadence,proto3" json:"cadence,omitempty"`                                    // human readable cadence (e.g., "24h")
	NextRunAt     string                 `protobuf:"bytes,2,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`             // ISO timestamp
	LastSuccessAt string                 `protobuf:"bytes,3,opt,name=last_success_at,json=lastSuccessAt,proto3" json:"last_success_at,omitempty"` // ISO timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleSummary) Reset() {
	*x = ScheduleSummary{}
	mi := &file_rag_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleSummary) ProtoMessage() {}

func (x *ScheduleSummary) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleSummary.ProtoReflect.Descriptor instead.
func (*ScheduleSummary) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{8}
}

func (x *ScheduleSummary) GetCadence() string {
	if x != nil {
		return x.Cadence
	}
	return ""
}

func (x *ScheduleSummary) GetNextRunAt() string {
	if x != nil {
		return x.NextRunAt
	}
	return ""
}

func (x *ScheduleSummary) GetLastSuccessAt() string {
	if x != nil {
		return x.LastSuccessAt
	}
	return ""
}

type EvictionTelemetry struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalEntries        int64                  `protobuf:"varint,1,opt,name=total_entries,json=totalEntries,proto3" json:"total_entries,omitempty"`
	TotalBytes          int64                  `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	BudgetBytes         int64                  `protobuf:"varint,3,opt,name=budget_bytes,json=budgetBytes,proto3" json:"budget_bytes,omitempty"`
	LastEvictionAt      string                 `protobuf:"bytes,4,opt,name=last_eviction_at,json=lastEvictionAt,proto3" json:"last_eviction_at,omitempty"` // ISO timestamp
	LastEvictionRemoved int64                  `protobuf:"varint,5,opt,name=last_eviction_removed,json=lastEvictionRemoved,proto3" json:"last_eviction_removed,omitempty"`
	LastEvictionBytes   int64                  `protobuf:"varint,6,opt,name=last_eviction_bytes,json=lastEvictionBytes,proto3" json:"last_eviction_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EvictionTelemetry) Reset() {
	*x = EvictionTelemetry{}
	mi := &file_rag_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictionTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictionTelemetry) ProtoMessage() {}

func (x *EvictionTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictionTelemetry.ProtoReflect.Descriptor instead.
func (*EvictionTelemetry) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{9}
}

func (x *EvictionTelemetry) GetTotalEntries() int64 {
	if x != nil {
		return x.TotalEntries
	}
	return 0
}

func (x *EvictionTelemetry) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *EvictionTelemetry) GetBudgetBytes() int64 {
	if x != nil {
		return x.BudgetBytes
	}
	return 0
}

func (x *EvictionTelemetry) GetLastEvictionAt() string {
	if x != nil {
		return x.LastEvictionAt
	}
	return ""
}

func (x *EvictionTelemetry) GetLastEvictionRemoved() int64 {
	if x != nil {
		return x.LastEvictionRemoved
	}
	return 0
}

func (x *EvictionTelemetry) GetLastEvictionBytes() int64 {
	if x != nil {
		return x.LastEvictionBytes
	}
	return 0
}

type GetStatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LatestJobId          string                 `protobuf:"bytes,1,opt,name=latest_job_id,json=latestJobId,proto3" json:"latest_job_id,omitempty"`
	LatestJobStatus      string                 `protobuf:"bytes,2,opt,name=latest_job_status,json=latestJobStatus,proto3" json:"latest_job_status,omitempty"`                  // running, completed, failed
	LatestJobCompletedAt string                 `protobuf:"bytes,3,opt,name=latest_job_completed_at,json=latestJobCompletedAt,proto3" json:"latest_job_completed_at,omitempty"` // ISO timestamp
	CacheDiskPct         float64                `protobuf:"fixed64,4,opt,name=cache_disk_pct,json=cacheDiskPct,proto3" json:"cache_disk_pct,omitempty"`                         // 0-100
	CacheHitRate         int64                  `protobuf:"varint,5,opt,name=cache_hit_rate,json=cacheHitRate,proto3" json:"cache_hit_rate,omitempty"`                          // Percent
	ActiveModels         []string               `protobuf:"bytes,6,rep,name=active_models,json=activeModels,proto3" json:"active_models,omitempty"`
	Progress             *IngestionProgress     `protobuf:"bytes,7,opt,name=progress,proto3" json:"progress,omitempty"`
	Schedule             *ScheduleSummary       `protobuf:"bytes,8,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Eviction             *EvictionTelemetry     `protobuf:"bytes,9,opt,name=eviction,proto3" json:"eviction,omitempty"`
	ManPagesProcessed    int64                  `protobuf:"varint,10,opt,name=man_pages_processed,json=manPagesProcessed,proto3" json:"man_pages_processed,omitempty"`
	WikiArticlesLoaded   int64                  `protobuf:"varint,11,opt,name=wiki_articles_loaded,json=wikiArticlesLoaded,proto3" json:"wiki_articles_loaded,omitempty"`
	IngestionErrors      []string               `protobuf:"bytes,12,rep,name=ingestion_errors,json=ingestionErrors,proto3" json:"ingestion_errors,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_rag_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetStatusResponse) GetLatestJobId() string {
	if x != nil {
		return x.LatestJobId
	}
	return ""
}

func (x *GetStatusResponse) GetLatestJobStatus() string {
	if x != nil {
		return x.LatestJobStatus
	}
	return ""
}

func (x *GetStatusResponse) GetLatestJobCompletedAt() string {
	if x != nil {
		return x.LatestJobCompletedAt
	}
	return ""
}

func (x *GetStatusResponse) GetCacheDiskPct() float64 {
	if x != nil {
		return x.CacheDiskPct
	}
	return 0
}

func (x *GetStatusResponse) GetCacheHitRate() int64 {
	if x != nil {
		return x.CacheHitRate
	}
	return 0
}

func (x *GetStatusResponse) GetActiveModels() []string {
	if x != nil {
		return x.ActiveModels
	}
	return nil
}

func (x *GetStatusResponse) GetProgress() *IngestionProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *GetStatusResponse) GetSchedule() *ScheduleSummary {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *GetStatusResponse) GetEviction() *EvictionTelemetry {
	if x != nil {
		return x.Eviction
	}
	return nil
}

func (x *GetStatusResponse) GetManPagesProcessed() int64 {
	if x != nil {
		return x.ManPagesProcessed
	}
	return 0
}

func (x *GetStatusResponse) GetWikiArticlesLoaded() int64 {
	if x != nil {
		return x.WikiArticlesLoaded
	}
	return 0
}

func (x *GetStatusResponse) GetIngestionErrors() []string {
	if x != nil {
		return x.IngestionErrors
	}
	return nil
}

type SubmitFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Rating        string                 `protobuf:"bytes,2,opt,name=rating,proto3" json:"rating,omitempty"` // positive, neutral, negative
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFeedbackRequest) Reset() {
	*x = SubmitFeedbackRequest{}
	mi := &file_rag_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFeedbackRequest) ProtoMessage() {}

func (x *SubmitFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFeedbackRequest.ProtoReflect.Descriptor instead.
func (*SubmitFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitFeedbackRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubmitFeedbackRequest) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *SubmitFeedbackRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type SubmitFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackId    string                 `protobuf:"bytes,1,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // open, triaged, resolved
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFeedbackResponse) Reset() {
	*x = SubmitFeedbackResponse{}
	mi := &file_rag_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFeedbackResponse) ProtoMessage() {}

func (x *SubmitFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFeedbackResponse.ProtoReflect.Descriptor instead.
func (*SubmitFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitFeedbackResponse) GetFeedbackId() string {
	if x != nil {
		return x.FeedbackId
	}
	return ""
}

func (x *SubmitFeedbackResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ControlStackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`                              // start, stop, restart
	ComposeFile   string                 `protobuf:"bytes,2,opt,name=compose_file,json=composeFile,proto3" json:"compose_file,omitempty"` // optional override for podman-compose path
	ConfigPath    string                 `protobuf:"bytes,3,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`    // optional Python server config
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlStackRequest) Reset() {
	*x = ControlStackRequest{}
	mi := &file_rag_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlStackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlStackRequest) ProtoMessage() {}

func (x *ControlStackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlStackRequest.ProtoReflect.Descriptor instead.
func (*ControlStackRequest) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{13}
}

func (x *ControlStackRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ControlStackRequest) GetComposeFile() string {
	if x != nil {
		return x.ComposeFile
	}
	return ""
}

func (x *ControlStackRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

type ControlStackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`   // echo of requested action
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`   // success, failed, in_progress
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // human-readable details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlStackResponse) Reset() {
	*x = ControlStackResponse{}
	mi := &file_rag_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlStackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlStackResponse) ProtoMessage() {}

func (x *ControlStackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlStackResponse.ProtoReflect.Descriptor instead.
func (*ControlStackResponse) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{14}
}

func (x *ControlStackResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ControlStackResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ControlStackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rag_service_proto protoreflect.FileDescriptor

const file_rag_service_proto_rawDesc = "" +
	"\n" +
	"\x11rag_service.proto\x12\vlinuxrag.v1\"\x9a\x01\n" +
	"\n" +
	"AskRequest\x12\x1d\n" +
	"\n" +
	"query_text\x18\x01 \x01(\tR\tqueryText\x12#\n" +
	"\rcontext_hints\x18\x02 \x03(\tR\fcontextHints\x12'\n" +
	"\x0fpreferred_model\x18\x03 \x01(\tR\x0epreferredModel\x12\x1f\n" +
	"\vallow_cache\x18\x04 \x01(\bR\n" +
	"allowCache\"\xc9\x01\n" +
	"\vAskResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vanswer_text\x18\x02 \x01(\tR\n" +
	"answerText\x123\n" +
	"\tcitations\x18\x03 \x03(\v2\x15.linuxrag.v1.CitationR\tcitations\x12\x1b\n" +
	"\tcache_hit\x18\x04 \x01(\bR\bcacheHit\x12(\n" +
	"\x10response_time_ms\x18\x05 \x01(\x03R\x0eresponseTimeMs\"x\n" +
	"\bCitation\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\x12\x1f\n" +
	"\vsource_path\x18\x04 \x01(\tR\n" +
	"sourcePath\"k\n" +
	"\x13RunIngestionRequest\x12(\n" +
	"\x10wiki_archive_ids\x18\x01 \x03(\tR\x0ewikiArchiveIds\x12*\n" +
	"\x11refresh_man_pages\x18\x02 \x01(\bR\x0frefreshManPages\"\xca\x01\n" +
	"\x14RunIngestionResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12.\n" +
	"\x13man_pages_processed\x18\x02 \x01(\x03R\x11manPagesProcessed\x126\n" +
	"\x17wiki_articles_processed\x18\x03 \x01(\x03R\x15wikiArticlesProcessed\x123\n" +
	"\x06errors\x18\x04 \x03(\v2\x1b.linuxrag.v1.IngestionErrorR\x06errors\"M\n" +
	"\x0eIngestionError\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x12\n" +
	"\x10GetStatusRequest\"u\n" +
	"\x11IngestionProgress\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12)\n" +
	"\x10percent_complete\x18\x02 \x01(\x01R\x0fpercentComplete\x12\x1f\n" +
	"\vretry_count\x18\x03 \x01(\x03R\n" +
	"retryCount\"s\n" +
	"\x0fScheduleSummary\x12\x18\n" +
	"\acadence\x18\x01 \x01(\tR\acadence\x12\x1e\n" +
	"\vnext_run_at\x18\x02 \x01(\tR\tnextRunAt\x12&\n" +
	"\x0flast_success_at\x18\x03 \x01(\tR\rlastSuccessAt\"\x8a\x02\n" +
	"\x11EvictionTelemetry\x12#\n" +
	"\rtotal_entries\x18\x01 \x01(\x03R\ftotalEntries\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes\x12!\n" +
	"\fbudget_bytes\x18\x03 \x01(\x03R\vbudgetBytes\x12(\n" +
	"\x10last_eviction_at\x18\x04 \x01(\tR\x0elastEvictionAt\x122\n" +
	"\x15last_eviction_removed\x18\x05 \x01(\x03R\x13lastEvictionRemoved\x12.\n" +
	"\x13last_eviction_bytes\x18\x06 \x01(\x03R\x11lastEvictionBytes\"\xca\x04\n" +
	"\x11GetStatusResponse\x12\"\n" +
	"\rlatest_job_id\x18\x01 \x01(\tR\vlatestJobId\x12*\n" +
	"\x11latest_job_status\x18\x02 \x01(\tR\x0flatestJobStatus\x125\n" +
	"\x17latest_job_completed_at\x18\x03 \x01(\tR\x14latestJobCompletedAt\x12$\n" +
	"\x0ecache_disk_pct\x18\x04 \x01(\x01R\fcacheDiskPct\x12$\n" +
	"\x0ecache_hit_rate\x18\x05 \x01(\x03R\fcacheHitRate\x12#\n" +
	"\ractive_models\x18\x06 \x03(\tR\factiveModels\x12:\n" +
	"\bprogress\x18\a \x01(\v2\x1e.linuxrag.v1.IngestionProgressR\bprogress\x128\n" +
	"\bschedule\x18\b \x01(\v2\x1c.linuxrag.v1.ScheduleSummaryR\bschedule\x12:\n" +
	"\beviction\x18\t \x01(\v2\x1e.linuxrag.v1.EvictionTelemetryR\beviction\x12.\n" +
	"\x13man_pages_processed\x18\n" +
	" \x01(\x03R\x11manPagesProcessed\x120\n" +
	"\x14wiki_articles_loaded\x18\v \x01(\x03R\x12wikiArticlesLoaded\x12)\n" +
	"\x10ingestion_errors\x18\f \x03(\tR\x0fingestionErrors\"h\n" +
	"\x15SubmitFeedbackRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\tR\x06rating\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"Q\n" +
	"\x16SubmitFeedbackResponse\x12\x1f\n" +
	"\vfeedback_id\x18\x01 \x01(\tR\n" +
	"feedbackId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"q\n" +
	"\x13ControlStackRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12!\n" +
	"\fcompose_file\x18\x02 \x01(\tR\vcomposeFile\x12\x1f\n" +
	"\vconfig_path\x18\x03 \x01(\tR\n" +
	"configPath\"`\n" +
	"\x14ControlStackResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x97\x03\n" +
	"\n" +
	"RagService\x128\n" +
	"\x03Ask\x12\x17.linuxrag.v1.AskRequest\x1a\x18.linuxrag.v1.AskResponse\x12S\n" +
	"\fRunIngestion\x12 .linuxrag.v1.RunIngestionRequest\x1a!.linuxrag.v1.RunIngestionResponse\x12J\n" +
	"\tGetStatus\x12\x1d.linuxrag.v1.GetStatusRequest\x1a\x1e.linuxrag.v1.GetStatusResponse\x12Y\n" +
	"\x0eSubmitFeedback\x12\".linuxrag.v1.SubmitFeedbackRequest\x1a#.linuxrag.v1.SubmitFeedbackResponse\x12S\n" +
	"\fControlStack\x12 .linuxrag.v1.ControlStackRequest\x1a!.linuxrag.v1.ControlStackResponseB?Z=github.com/linux-rag/linux-rag/internal/contracts;contractspbb\x06proto3"

var (
	file_rag_service_proto_rawDescOnce sync.Once
	file_rag_service_proto_rawDescData []byte
)

func file_rag_service_proto_rawDescGZIP() []byte {
	file_rag_service_proto_rawDescOnce.Do(func() {
		file_rag_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_service_proto_rawDesc), len(file_rag_service_proto_rawDesc)))
	})
	return file_rag_service_proto_rawDescData
}

var file_rag_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_rag_service_proto_goTypes = []any{
	(*AskRequest)(nil),             // 0: linuxrag.v1.AskRequest
	(*AskResponse)(nil),            // 1: linuxrag.v1.AskResponse
	(*Citation)(nil),               // 2: linuxrag.v1.Citation
	(*RunIngestionRequest)(nil),    // 3: linuxrag.v1.RunIngestionRequest
	(*RunIngestionResponse)(nil),   // 4: linuxrag.v1.RunIngestionResponse
	(*IngestionError)(nil),         // 5: linuxrag.v1.IngestionError
	(*GetStatusRequest)(nil),       // 6: linuxrag.v1.GetStatusRequest
	(*IngestionProgress)(nil),      // 7: linuxrag.v1.IngestionProgress
	(*ScheduleSummary)(nil),        // 8: linuxrag.v1.ScheduleSummary
	(*EvictionTelemetry)(nil),      // 9: linuxrag.v1.EvictionTelemetry
	(*GetStatusResponse)(nil),      // 10: linuxrag.v1.GetStatusResponse
	(*SubmitFeedbackRequest)(nil),  // 11: linuxrag.v1.SubmitFeedbackRequest
	(*SubmitFeedbackResponse)(nil), // 12: linuxrag.v1.SubmitFeedbackResponse
	(*ControlStackRequest)(nil),    // 13: linuxrag.v1.ControlStackRequest
	(*ControlStackResponse)(nil),   // 14: linuxrag.v1.ControlStackResponse
}
var file_rag_service_proto_depIdxs = []int32{
	2,  // 0: linuxrag.v1.AskResponse.citations:type_name -> linuxrag.v1.Citation
	5,  // 1: linuxrag.v1.RunIngestionResponse.errors:type_name -> linuxrag.v1.IngestionError
	7,  // 2: linuxrag.v1.GetStatusResponse.progress:type_name -> linuxrag.v1.IngestionProgress
	8,  // 3: linuxrag.v1.GetStatusResponse.schedule:type_name -> linuxrag.v1.ScheduleSummary
	9,  // 4: linuxrag.v1.GetStatusResponse.eviction:type_name -> linuxrag.v1.EvictionTelemetry
	0,  // 5: linuxrag.v1.RagService.Ask:input_type -> linuxrag.v1.AskRequest
	3,  // 6: linuxrag.v1.RagService.RunIngestion:input_type -> linuxrag.v1.RunIngestionRequest
	6,  // 7: linuxrag.v1.RagService.GetStatus:input_type -> linuxrag.v1.GetStatusRequest
	11, // 8: linuxrag.v1.RagService.SubmitFeedback:input_type -> linuxrag.v1.SubmitFeedbackRequest
	13, // 9: linuxrag.v1.RagService.ControlStack:input_type -> linuxrag.v1.ControlStackRequest
	1,  // 10: linuxrag.v1.RagService.Ask:output_type -> linuxrag.v1.AskResponse
	4,  // 11: linuxrag.v1.RagService.RunIngestion:output_type -> linuxrag.v1.RunIngestionResponse
	10, // 12: linuxrag.v1.RagService.GetStatus:output_type -> linuxrag.v1.GetStatusResponse
	12, // 13: linuxrag.v1.RagService.SubmitFeedback:output_type -> linuxrag.v1.SubmitFeedbackResponse
	14, // 14: linuxrag.v1.RagService.ControlStack:output_type -> linuxrag.v1.ControlStackResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_rag_service_proto_init() }
func file_rag_service_proto_init() {
	if File_rag_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_service_proto_rawDesc), len(file_rag_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_service_proto_goTypes,
		DependencyIndexes: file_rag_service_proto_depIdxs,
		MessageInfos:      file_rag_service_proto_msgTypes,
	}.Build()
	File_rag_service_proto = out.File
	file_rag_service_proto_goTypes = nil
	file_rag_service_proto_depIdxs = nil
}
