# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import rag_service_pb2 as rag__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rag_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RagServiceStub(object):
    """RAG retrieval and admin service consumed by the Go CLIs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ask = channel.unary_unary(
                '/linuxrag.v1.RagService/Ask',
                request_serializer=rag__service__pb2.AskRequest.SerializeToString,
                response_deserializer=rag__service__pb2.AskResponse.FromString,
                _registered_method=True)
        self.RunIngestion = channel.unary_unary(
                '/linuxrag.v1.RagService/RunIngestion',
                request_serializer=rag__service__pb2.RunIngestionRequest.SerializeToString,
                response_deserializer=rag__service__pb2.RunIngestionResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/linuxrag.v1.RagService/GetStatus',
                request_serializer=rag__service__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=rag__service__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.SubmitFeedback = channel.unary_unary(
                '/linuxrag.v1.RagService/SubmitFeedback',
                request_serializer=rag__service__pb2.SubmitFeedbackRequest.SerializeToString,
                response_deserializer=rag__service__pb2.SubmitFeedbackResponse.FromString,
                _registered_method=True)
        self.ControlStack = channel.unary_unary(
                '/linuxrag.v1.RagService/ControlStack',
                request_serializer=rag__service__pb2.ControlStackRequest.SerializeToString,
                response_deserializer=rag__service__pb2.ControlStackResponse.FromString,
                _registered_method=True)


class RagServiceServicer(object):
    """RAG retrieval and admin service consumed by the Go CLIs.
    """

    def Ask(self, request, context):
        """Submit a natural-language query and receive an answer with citations.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunIngestion(self, request, context):
        """Trigger ingestion for man pages and selected wiki archives.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Provide current system status including cache usage and index freshness.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitFeedback(self, request, context):
        """Record user feedback for a prior answer session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlStack(self, request, context):
        """Manage lifecycle of the knowledge stack (start, stop, restart).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ask': grpc.unary_unary_rpc_method_handler(
                    servicer.Ask,
                    request_deserializer=rag__service__pb2.AskRequest.FromString,
                    response_serializer=rag__service__pb2.AskResponse.SerializeToString,
            ),
            'RunIngestion': grpc.unary_unary_rpc_method_handler(
                    servicer.RunIngestion,
                    request_deserializer=rag__service__pb2.RunIngestionRequest.FromString,
                    response_serializer=rag__service__pb2.RunIngestionResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=rag__service__pb2.GetStatusRequest.FromString,
                    response_serializer=rag__service__pb2.GetStatusResponse.SerializeToString,
            ),
            'SubmitFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitFeedback,
                    request_deserializer=rag__service__pb2.SubmitFeedbackRequest.FromString,
                    response_serializer=rag__service__pb2.SubmitFeedbackResponse.SerializeToString,
            ),
            'ControlStack': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlStack,
                    request_deserializer=rag__service__pb2.ControlStackRequest.FromString,
                    response_serializer=rag__service__pb2.ControlStackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'linuxrag.v1.RagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('linuxrag.v1.RagService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagService(object):
    """RAG retrieval and admin service consumed by the Go CLIs.
    """

    @staticmethod
    def Ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxrag.v1.RagService/Ask',
            rag__service__pb2.AskRequest.SerializeToString,
            rag__service__pb2.AskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunIngestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxrag.v1.RagService/RunIngestion',
            rag__service__pb2.RunIngestionRequest.SerializeToString,
            rag__service__pb2.RunIngestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxrag.v1.RagService/GetStatus',
            rag__service__pb2.GetStatusRequest.SerializeToString,
            rag__service__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxrag.v1.RagService/SubmitFeedback',
            rag__service__pb2.SubmitFeedbackRequest.SerializeToString,
            rag__service__pb2.SubmitFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlStack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/linuxrag.v1.RagService/ControlStack',
            rag__service__pb2.ControlStackRequest.SerializeToString,
            rag__service__pb2.ControlStackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
